### PR TITLE
Merge Emscripten downstream changes to emscripten-libs-16

### PR DESCRIPTION
**Pull request by aheejin**
Given that I started
https://github.com/emscripten-core/emscripten/pull/20405 and OOO for nearly a month and then in the meantime llvm 17.0.4 came out, I'd like to update to not 17.0.3 but 17.0.4, with the most recent downstream changes. These are the downstream changes happened during the last month.

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]
Great!

**Comment by sbc100** [comment]
Can you land with "Rebase and merge" ?

**Comment by aheejin** [comment]
Can do, but I wonder what the difference is between that and "squash and merge"? (given that there is only a single commit anyway?)

**Comment by sbc100** [comment]
Sorry yes I think "squash and merge" is what I meant.

What I want to avoid is the extra merge commit and non-linear history.

**Comment by sbc100** [comment]
I think when you have a single commit "rebase and merge" and "squash and merge" are the same thing.. at least it sounds like they should be since the "squash" part should be a no-op in that case.

**Comment by aheejin** [comment]
> Sorry yes I think "squash and merge" is what I meant.
> 
> What I want to avoid is the extra merge commit and non-linear history.

Oh sorry I missed this comment and did "Rebase and merge` as you originally requested... now there seems to be a merge commit ;(

**Pull request merged**
